db/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add paths from the socialvoiceapp application
from django.urls import include
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('socialvoiceapp/', include('socialvoiceapp.urls')),
    path('', RedirectView.as_view(url='socialvoiceapp/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

socialvoiceapp/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.feed_view, name='index'),
    # path('profile/<int:id>', views.ProfileDetailView.as_view(), name='profile'), # wasnt working  -will fix later
    path('userprofile', views.profile_view, name='profile-detail'),
    # path('feed', views.feed_view, name='feed'),
    # path('register', views.profile_create_view, name='register'),
    path('register', views.create_user_view, name='register'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
]

socialvoiceapp/models.py
from django.db import models
# from djongo import models
from django.contrib.auth.models import User
from .validators import validate_audio_file_extension, validate_image_file_extension

from django.conf import settings
from djongo.storage import GridFSStorage
from django.db.models.signals import post_save
from django.dispatch import receiver

from datetime import datetime
import django

# Define your GrifFSStorage instance
grid_fs_storage = GridFSStorage(collection='myfiles', base_url=''.join([settings.BASE_URL, 'myfiles/']))

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Profile(models.Model):
    # This model is extended from the default User model, it deals with data outside of authentication
    # default user model attributes:
        # username
        # password
        # email  

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    avatar = models.ImageField(upload_to='avatars', storage=grid_fs_storage, null=True, validators=[validate_image_file_extension])

class AudioMessage(models.Model):
    managed = True
    audio_data = models.FileField(upload_to='messages', storage=grid_fs_storage, null=True, validators=[validate_audio_file_extension])
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    upload_time = models.DateTimeField(default=django.utils.timezone.now)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

socialvoiceapp/forms.py
from django import forms
# from djongo import forms
from django.contrib.auth.models import User
from django.forms import widgets
from django.forms.fields import DateTimeField
from socialvoiceapp.models import Profile, City, Country, AudioMessage
from django.contrib.auth.forms import UserCreationForm

#
class UserForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ProfileCreationForm(forms.ModelForm):
    terms_and_conditions = forms.BooleanField(required=True)

    class Meta:
        model = Profile
        fields = ['country', 'city']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'country', 'city']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

class AddAudioMessageForm(forms.ModelForm):
    class Meta:
        model = AudioMessage
        fields = ['audio_data', 'user']
        widgets = {'user': forms.HiddenInput()}

class DeleteAudioMessageForm(forms.ModelForm):
    class Meta:
        model = AudioMessage
        fields = []

socialvoiceapp/views.py
# from socialvoiceapp.models import
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse, HttpResponse
from datetime import datetime
from datetime import date, timedelta
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import FormView,TemplateView
from django.contrib.auth.models import User
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from socialvoiceapp.models import Profile, Country, City, AudioMessage
from .forms import AddAudioMessageForm, DeleteAudioMessageForm, ProfileUpdateForm

from .forms import ProfileCreationForm, UserForm

from django.db import transaction
from pymongo import MongoClient
import gridfs
from gridfs import GridFS
from bson import ObjectId
import os

# Create your views here.
#@login_required
def index_view(request):
    """View function for home page of site."""

    context = {

    }

    if request.user.is_authenticated :
        # Redirect to a success page.
        return render(request, 'feed.html', context=context)
    else:
        # Return an 'invalid login' error message.
        return render(request, 'index.html', context=context)
#
# class ProfileCreateView(CreateView):
#     model = Profile
#     # template_name = 'profile_form.html'
#     fields = ( 'country', 'city')
#     success_url = reverse_lazy('feed')


# will change to class based view
@login_required
def profile_view(request):
    user = Profile.objects.get(user=request.user.id)
    client = MongoClient('mongo', 27017, username='root', password='mongoadmin')
    db = client['socialvoice']

    audio_coll = db['socialvoiceapp_audiomessage']
    audio_messages = audio_coll.find(
        {'user_id': request.user.id}
    ).sort('upload_time', -1)

    messages = []
    for i in range(int(audio_messages.count())):
        messages.append({
        'id': audio_messages[i]['_id'],
        'audio_data': audio_messages[i]['audio_data'],
        'user_id': audio_messages[i]['user_id'],
        'upload_time': audio_messages[i]['upload_time'],
        'audio_id': audio_messages[i]['audio_data'].split('/')[1].split('.')[0]
        })

    addform = AddAudioMessageForm(request.POST, request.FILES, initial = {'user': request.user.id}) # Load the add audio form, with the user field initalized as the logged in user
    addform.fields['audio_data'].label = 'Audio' # Changes the audio field name in the form
    addform.fields['user'].disabled = True # The user input is selected by default as the current logged in user, no changes should be allowed

    deleteform = DeleteAudioMessageForm(request.POST, request.FILES)

    if request.method == "POST" and request.POST['action'] == 'Yes':
        audio_files_coll = db['myfiles.messages.files']
        audio_chuncks_coll = db['myfiles.messages.chunks']

        #Delete all chuncks with matching files_id to files id
        file_name = str(request.POST['pk']).split('/')[1]
        file_id = audio_files_coll.find_one({'filename': file_name})['_id']
        audio_chuncks_coll.delete_many({'files_id': file_id})


        #Delete all files with matching filename to audio message
        audio_files_coll.delete_many({'filename': file_name})

        #Delete audio message with id matching pk
        audio_coll.delete_one({'audio_data': request.POST['pk']})

        return HttpResponseRedirect('')

    #Build avatar
    avatar_fs = gridfs.GridFS(db, collection='myfiles.avatars')

    avatar_file_name = user.avatar.name.split('/')[1]  #Split the avatar url to get the file name to be used in query for the avatar files
    meta = avatar_fs.get_version(filename=avatar_file_name) #Gets file details using filename from profile
    avatar_bucket = gridfs.GridFSBucket(db, bucket_name='myfiles.avatars')
    avatar_file = open('socialvoiceapp/static/'+ user.avatar.name, 'wb')  #Write to file
    avatar_bucket.download_to_stream(file_id=meta._id, destination=avatar_file) #Download file to static folder
    avatar_file.close()

    #Update user details
    updateUserForm = ProfileUpdateForm(request.POST, request.FILES)#, initial={'country': user.country, 'city': user.city})

    if request.method == 'POST':
        #Add audio
        if request.POST['action'] == 'Upload':
            if addform.is_valid(): # Only allows for audio to be saved if valid audio file is uploaded
                addform.save()
                return HttpResponseRedirect('')
            #Update User Profile details
        elif request.POST['action'] == 'Update':
            if updateUserForm.is_valid():
                new_country = int(request.POST['country'])
                new_city = int(request.POST['city'])
                profiles_coll = db['socialvoiceapp_profile']
                #Try to 
                
                try:
                    if request.FILES['avatar']:
                        avatar = request.FILES['avatar']

                        avatar_files_coll = db['myfiles.avatars.files']
                        avatar_chuncks_coll = db['myfiles.avatars.chunks']

                        file_name=user.avatar.name.split('/')[1]
                        if not file_name.startswith("default"):
                            #Delete all chuncks with matching files_id to files id
                            file_id = avatar_files_coll.find_one({'filename': file_name})['_id']
                            avatar_chuncks_coll.delete_many({'files_id': file_id})
                            
                        
                            avatar_files_coll.delete_many({'filename': file_name})

                        profiles_coll.update_one(
                            {'user_id': user.user_id}, #Filter
                            {'$set': {'country_id': new_country, 'city_id': new_city, 'avatar': str('avatars/' + str(request.user) + str( avatar.name))}} #Update data                    
                        )
                        
                        #CREATE NEW DOCUMENT FOR IMAGE
                        avatar_fs.put(avatar, filename=str(str(request.user) + str(avatar.name)), contentType=avatar.content_type)
                        
                except:
                    if request.POST['avatar'] == '':
                        profiles_coll.update_one(
                            {'user_id': user.user_id}, #Filter
                            {'$set': {'country_id': new_country, 'city_id': new_city}} #Update data                    
                    )
                    

    context = {
        'profile': user,
        'messages': messages,
        'addAudioForm': addform,
        'deleteAudioForm': deleteform,
        'updateUserForm': updateUserForm
    }

    return render(request, 'user_profile.html', context=context)

# class ProfileDetailView(LoginRequiredMixin, generic.DetailView):
#     model = User


@login_required
def feed_view(request):
    client = MongoClient('mongo', 27017, username='root', password='mongoadmin')
    db = client['socialvoice']

    avatar_fs = gridfs.GridFS(db, collection='myfiles.avatars')
    audio_fs = gridfs.GridFS(db, collection='myfiles.messages')

    user_coll = db['socialvoiceapp_profile']
    auth_user_coll = db['auth_user']

    users_ids = user_coll.find({'city_id': Profile.objects.get(user=request.user.id).city_id}, {'user_id', 'avatar'})

    users = []
    ids_to_search = []

    for i in users_ids:
        ids_to_search.append(i['user_id'])

        users.append(
            { 'user':auth_user_coll.find_one(
                        { #Query
                            'id': i['user_id']
                        },
                        { #Fields to get
                            'username','is_active', 'date_joined'
                        }
                    ),
                    'user_id': i['user_id'],
                    'avatar_id': i['avatar']
                }
        )
        print(int(i['user_id']))
        #Build avatar
        if i['avatar'] is '':
            file_name = 'default.png'
            profiles_coll = db['socialvoiceapp_profile']
            profiles_coll.update_one(
                            {'user_id': int(i['user_id'])}, #Filter
                            {'$set': {'avatar': 'avatars/default.png'}} #Update data                    
                    )         

        else:
            file_name = i['avatar'].split('/')[1]  #Split the avatar url to get the file name to be used in query for the avatar files
            meta = avatar_fs.get_version(filename=file_name) #Gets file details using filename from profile
            avatar_bucket = gridfs.GridFSBucket(db, bucket_name='myfiles.avatars')
            avatar_file = open('socialvoiceapp/static/'+i['avatar'], 'wb')  #Write to file
            avatar_bucket.download_to_stream(file_id=meta._id, destination=avatar_file) #Download file to static folder
            avatar_file.close()

    audio_coll = db['socialvoiceapp_audiomessage']
    audio_messages = audio_coll.find(
        {
            'user_id': {"$in": ids_to_search}
        }
    ).sort('upload_time', -1)

    messages = []
    for message in audio_messages:
        messages.append({
            'audio':message,
            'profile': auth_user_coll.find_one(
                {#Query
                    'id': message['user_id']
                },
                {#Fields to get
                    'username', 'is_active', 'date_joined'
                }
            ),
            'avatar': user_coll.find_one(
                {#Query
                    'user_id': message['user_id']
                },

socialvoiceapp/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>SocialVoice</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="shortcut icon" type="image/png" href="{% static 'media/favicon.png' %}"/>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- style sheets and font icons  -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/font-icons.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/theme-vendors.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}" />
  <!-- revolution slider -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/settings.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/layers.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'revolution/css/navigation.css' %}">

</head>
<body>

    
  {% include 'navbar.html' %}
  {% block content %}
  {% endblock %}

    <!-- <div id="cookieConsent">
        <div id="closeCookieConsent">x</div>
        This website is using cookies. <a href="#" target="_blank">More info</a>. <a class="cookieConsentOK">That's Fine</a>
    </div> -->
    <div class=’cookie-banner’ style='display: always'>
        <p>
            By using our website, you agree to our 
            <a href=’insert-link’>cookie policy</a>
          </p>
        <button class=’close’>&times;</button>
        </div>

  {% include 'footer.html' %}


    <script type="text/javascript">
            console
            if (localStorage.getItem('cookieSeen') != 'shown') {
            $('.cookie-banner').delay(2000).fadeIn();
            localStorage.setItem('cookieSeen','shown')
            };
            $('.close').click(function() {
            $('.cookie-banner').fadeOut();
            })
    </script>

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/theme-vendors.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

    <!-- revolution js files -->
    <script type="text/javascript" src="{% static 'js/jquery.themepunch.tools.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.themepunch.revolution.min.js' %}"></script>


        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.video.min.js' %}"></script>

        <script type="text/javascript" src="{% static 'js/login.js' %}"></script>

      <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.slideanims.min.js' %"></script>
      <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.layeranimation.min.js' %"></script>
      <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.navigation.min.js' %"></script>
      <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.parallax.min.js' %"></script>

<script type="text/javascript">
            var revapi266,
                    tpj;
            (function () {
                if (!/loaded|interactive|complete/.test(document.readyState))
                    document.addEventListener("DOMContentLoaded", onLoad);
                else
                    onLoad();
                function onLoad() {
                    if (tpj === undefined) {
                        tpj = jQuery;
                        if ("off" == "on")
                            tpj.noConflict();
                    }
                    if (tpj("#rev_slider_32_1").revolution == undefined) {
                        revslider_showDoubleJqueryError("#rev_slider_32_1");
                    } else {
                        revapi266 = tpj("#rev_slider_32_1").show().revolution({
                            sliderType: "standard",
                            jsFileLocation: "revolution/js/",
                            sliderLayout: "fullscreen",
                            dottedOverlay: "none",
                            delay: 9000,
                            navigation: {
                                keyboardNavigation: "on",
                                keyboard_direction: "horizontal",
                                mouseScrollNavigation: "off",
                                mouseScrollReverse: "default",
                                onHoverStop: "off",
                                touch: {
                                    touchenabled: "on",
                                    touchOnDesktop: "on",
                                    swipe_threshold: 75,
                                    swipe_min_touches: 1,
                                    swipe_direction: "horizontal",
                                    drag_block_vertical: false
                                }
                            },
                            parallax: {
                                type: "mouse",
                                origo: "slidercenter",
                                speed: 2000,
                                levels: [2, 3, 4, 5, 6, 7, 12, 16, 10, 50, 46, 47, 48, 49, 50, 55],
                                type: "mouse",
                                disable_onmobile: "on"
                            },
                            responsiveLevels: [1240, 1025, 778, 480],
                            visibilityLevels: [1920, 1500, 1025, 768],
                            gridwidth: [1200, 1025, 778, 480],

                            lazyType: "none",
                            shadow: 0,
                            spinner: "spinner5",
                            stopLoop: "on",
                            stopAfterLoops: 0,
                            stopAtSlide: 1,
                            shuffle: "off",
                            autoHeight: "on",
                            fullScreenAutoWidth: "on",
                            fullScreenAlignForce: "on",
                            fullScreenOffsetContainer: "",
                            fullScreenOffset: "",
                            disableProgressBar: "on",
                            hideThumbsOnMobile: "off",
                            hideSliderAtLimit: 0,
                            hideCaptionAtLimit: 0,
                            hideAllCaptionAtLimit: 0,
                            debugMode: false,
                            fallbacks: {
                                simplifyAll: "off",
                                nextSlideOnWindowFocus: "off",
                                disableFocusListener: false,
                            }
                        });
                    }
                    ; /* END OF revapi call */
                }
                ; /* END OF ON LOAD FUNCTION */
            }()); /* END OF WRAPPING FUNCTION */
        </script>
        
        <script>
            $('#message a').click(function(){
                $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
            });
        </script>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#login-form").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>


</body>
</html>

socialvoiceapp/templates/cookies.html
<div class='cookie-banner' style='display: none'>
    <p>
        By using our website, you agree to our 
        <a href='insert-link;'>cookie policy</a>
        </p>
    <button class='close'>&times;</button>
</div>

<script>
    if (localStorage.getItem('cookieSeen') != 'shown') {
  $('.cookie-banner').delay(2000).fadeIn();
  localStorage.setItem('cookieSeen','shown')
};
$('.close').click(function() {
  $('.cookie-banner').fadeOut();
})
</script>

socialvoiceapp/templates/navbar.html
<!-- start header -->
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent header-light fixed-top navbar-boxed header-reverse-scroll">
        <div class="container-fluid nav-header-container">
            <div class="col-5 col-lg-2 pl-lg-0 mr-auto mr-lg-0">
                <a class="navbar-brand" href="index.html">
                    <img src="images/logo-black.png" data-at2x="images/logo-black@2x.png" alt="" class="default-logo">
                    <img src="images/logo-black.png" data-at2x="images/logo-black@2x.png" alt="" class="alt-logo">
                    <img src="images/logo-black.png" data-at2x="images/logo-black@2x.png" class="mobile-logo" alt="">
                </a>
            </div>
            <div class="col-auto col-lg-8 md-position-initial md-no-padding">
                <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-label="Toggle navigation">
                    <span class="navbar-toggler-line"></span>
                    <span class="navbar-toggler-line"></span>
                    <span class="navbar-toggler-line"></span>
                    <span class="navbar-toggler-line"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                    <ul class="navbar-nav alt-font">
                        {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'index'%}" class="nav-link">Feed</a>
                        </li>
                        <li>
                            <a href="{% url 'profile-detail'%}" class="nav-link">Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'logout'%}?next={{request.path}}" class="nav-link">Logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'index'%}" class="nav-link">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'login'%}?next={{request.path}}" class="nav-link">Login/Register</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="col-auto col-lg-2 text-right hidden-xs px-lg-0">
                <div class="header-social-icon d-inline-block">
                    <a href="http://www.facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a>
                    <a href="http://www.twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
                </div>
            </div>
        </div>
    </nav>
</header>
<!-- end header -->

socialvoiceapp/templates/voicememos.html
{% load static %}

<audio class="audio-player" controls="controls">
  <source src="static/{{audio}}" type="audio/ogg" />
  <source src="static/{{audio}}" type="audio/mpeg" />
  Your browser does not support the audio element.
</audio>